name: Check Deploy File

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:

jobs:
  short-circuit:
    uses: DEMGroup/.github/.github/workflows/short-circuit.yml@main
    with:
      short-circuit-label: "deploy-file-exists"

  check-project-type:
    needs: [short-circuit]
    if: needs.short-circuit.outputs.short-circuit != 'true'
    uses: DEMGroup/.github/.github/workflows/checks/check-project-type.yml@main

  check-deploy-file:
    needs: [check-project-type]
    if: needs.check-project-type.outputs.isDotnet == 'true' || needs.check-project-type.outputs.isDotnet == true
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if deploy.yml exists
        id: check-file
        run: |
          if [ -f ".github/workflows/deploy.yml" ]; then
            exit 0
          else
            echo "::error  title=Deploy File is Missing::Could not find Deploy.yml"
            exit 1
          fi

      - name: Add dotnet label to PR
        id: label-already-checked-deploy
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ github.token }}
          labels: deploy-file-exists
