name: Send message about issues to discord

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned]
  workflow_call:

jobs:
  notify-discord-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Cache timeout
        id: cache-timeout
        uses: actions/cache@v3
        with:
          path: issues-sent
          key: issue-${{ github.event.issue.id }}

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Check for hook url
        env:
          PR_WEBHOOK_URL: ${{ secrets.PR_WEBHOOK_URL }}
        if: ${{ env.PR_WEBHOOK_URL == '' }}
        run: |
          echo '## 🏴💀 You are missing `secrets.PR_WEBHOOK_URL` from your repository. Please add it [here](https://github.com/${{github.repository_owner}}/settings/secrets/actions). 💀🏴' >> $GITHUB_STEP_SUMMARY
          exit 1

      - uses: actions/checkout@v3
      - name: Set vars
        id: vars
        run: |
          issueLink=$(echo "${{github.repository}} Issue #${{ github.event.issue.number }}" | sed s/"DEMGroup\/"//)


          if (${{ github.event.issue.body == '' }}); then
            descTitle=""
            descBody=""
          else
            echo  "descBody<<EOF"  >> $GITHUB_ENV
            echo -e "${{github.event.issue.body}}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

          images=($(grep -Eo "https?://[^][ ]+\.(jpg|png|gif|jpeg)" <<< "$descBody"))
          for i in ${iamges[@]}; do
            imageObj=
          echo "botName=$(echo "${{github.repository}} Issue Hook Bot" | sed 's/DEMGroup\///g')" >> $GITHUB_OUTPUT
          echo "issueTitle=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "descriptionLabel=$descTitle" >> $GITHUB_OUTPUT
          echo "issueLink=$issueLink" >> $GITHUB_OUTPUT

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.PR_WEBHOOK_URL }}
          username: "${{ steps.vars.outputs.botName }}"
          avatar-url: "https://app.aesircrypto.com/assets/logo.png"
          embed-title: "${{ steps.vars.outputs.issueTitle }}"
          embed-description:
            "**Title**: ${{ github.event.pull_request.title }}\n
            **Link**: [${{steps.vars.outputs.issueLink}}](${{github.event.pull_request.html_url}})\n
            **Author**: <@${{ github.event.pull_request.user.login }}>\n
            ${{ steps.vars.outputs.descriptionLabel }} \n ${{ env.descBody }}"

      - name: Add the pr comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            ### :envelope_with_arrow: ${{ steps.vars.outputs.botName }} Sent a messsage to discord for this PR :outbox_tray:
            **Title**: ${{ github.event.pull_request.title }}
            **Link**: [${{steps.vars.outputs.prTitle}}](${{github.event.issue.url}})
            **Author**: @${{ github.event.issue.user }}
            ${{ steps.vars.outputs.descriptionLabel }}
            ${{ steps.vars.outputs.descriptionBody }}
            If you add a `wip` label before submitting it will skip this next time.

      - name: Add dotnet label to PR
        id: label-it-pr-sent
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ github.token }}
          labels: discord-pr-sent

          # hold for maybe image grep

          # images=($(grep -Eo "https?://[^][ ]+\.(jpg|png|gif|jpeg)" <<< "$descBody"))
          # for i in ${images[@]}; do
          #   imageObj=
