name: "Close stale issues and PR"
on:
  # schedule:
  #   - cron: "30 1 * * *"
  workflow_call:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: [self-hosted]
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-stale: 30
          days-before-pr-close: 14
          exempt-pr-labels: wip
