name: Build and Test - New

on:
  pull_request:
  workflow_call:

jobs:
  check-project-type-new:
    # skip if it isn't a PR to (default = main) or direct call
    if: ${{ github.event_name == 'workflow_call' || (github.event_name == 'pull_request' && github.base_ref == github.event.repository.default_branch) }}
    uses: DEMGroup/.github/.github/workflows/check-project-type.yml@main

  build-dotnet-new:
    needs: [check-project-type-new]
    if: ${{needs.check-project-type-new.outputs.isDotnet == 'true' && needs.check-project-type-new.outputs.isNode == 'false'}}
    uses: DEMGroup/.github/.github/workflows/build-dotnet-new.yml@main

  build-typescript-new:
    needs: [check-project-type-new]
    if: ${{ needs.check-project-type-new.outputs.isDotnet == 'false' && needs.check-project-type-new.outputs.isNode == 'true'}}
    uses: DEMGroup/.github/.github/workflows/build-typescript.yml@main
