name: Build and Test Dotnet - New

on:
  workflow_call:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build-dotnet-new:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ github.event.repository.name }}-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj')}}
          restore-keys: ${{ github.event.repository.name }}-${{ runner.os }}-nuget-
      - name: Add Github Package Source
        run: dotnet nuget add source --username DEMGroup --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github.com "https://nuget.pkg.github.com/DEMGroup/index.json"
      - name: Install dependencies
        run: dotnet restore -r linux-x64
      - name: Build
        run: dotnet build -v=q --configuration Release --no-restore
      - name: Test and Report
        id: test-report
        uses: zyborg/dotnet-tests-report@v1.4.4
        with:
          no_restore: true
          no_build: true
          report_name: ${{ github.event.repository.name }}-${{ runner.os }}-test-results-MMddyyyy
          report_title: ${{ github.event.repository.name }} ${{ runner.os }} Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          set_check_status_from_test_outcome: true
          fail_build_on_failed_tests: true
      - name: Add the pr comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            ### :test_tube: Check the test output HTML :heavy_check_mark: :x:
            ${{ steps.test-report.outputs.test_results_path }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ runner.os }}-test-results-MMddyyyy-${{ hashFiles('**/*.csproj')}}
          path: ${{ steps.test-report.outputs.test_results_path }}/*
