name: Check Project type (and guard pr for default branch)

on:
  workflow_call:
    outputs:
      isDotnet:
        description: Boolean value for if a project is dotnet
        value: ${{ jobs.check-project-type.outputs.isDotnet }}
      isNode:
        description: Boolean value for if a project is node
        value: ${{ jobs.check-project-type.outputs.isNode }}

jobs:
  check-project-type:
    runs-on: ubuntu-latest
    outputs:
      isDotnet: ${{ steps.check.outputs.isDotnet }}
      isNode: ${{ steps.check.outputs.isNode }}
    steps:
    - uses: actions/checkout@v3
    - name: Project Type Checker
      id: check
      run: |
        isDotnet=false
        if test -n "$(find . -name '*.sln')"; then
            isDotnet=true
        fi
        echo "isDotnet=$isDotnet" >> $GITHUB_OUTPUT
        isNode=false
        if test -n "$(find . -name 'package.json')"; then
            isNode=true
        fi
        echo "isNode=$isNode" >> $GITHUB_OUTPUT