name: Check Project type (and guard pr for default branch)

on:
  workflow_call:
    outputs:
      isDotnet:
        description: Boolean value for if a project is dotnet
        value: ${{ jobs.check-project-type.outputs.isDotnet || contains(github.event.pull_request.labels.*.name, 'dotnet') }}
      isNode:
        description: Boolean value for if a project is node
        value: ${{ jobs.check-project-type.outputs.isNode || contains(github.event.pull_request.labels.*.name, 'node') }}

jobs:
  sc1:
    uses: DEMGroup/.github/.github/workflows/short-circuit.yml@main
    with:
      short-circuit-label: 'node'
  sc2:
    uses: DEMGroup/.github/.github/workflows/short-circuit.yml@main
    with:
      short-circuit-label: 'dotnet'


  check-project-type:
    needs: [sc1, sc2]
    if: needs.sc1.outputs.short-circuit == 'false' && needs.sc2.outputs.short-circuit == 'false'
    runs-on: ubuntu-latest
    outputs:
      isDotnet: ${{ steps.check.outputs.isDotnet }}
      isNode: ${{ steps.check.outputs.isNode }}
    steps:
    - uses: actions/checkout@v3
    - name: Project Type Checker
      id: check
      run: |
        isDotnet=false
        if test -n "$(find . -name '*.sln')"; then
            isDotnet=true
        fi
        echo "isDotnet=$isDotnet" >> $GITHUB_OUTPUT
        isNode=false
        if test -n "$(find . -name 'package.json')"; then
            isNode=true
        fi
        echo "isNode=$isNode" >> $GITHUB_OUTPUT
    - name: Add dotnet label to PR
      id: label-it-dotnet
      if: steps.check.outputs.isDotnet == 'true'
      uses: actions-ecosystem/action-add-labels@v1.1.0
      with:
        github_token: ${{ github.token }}
        labels: dotnet
    - name: Add node label to PR
      id: label-it-node
      if: steps.check.outputs.isNode == 'true'
      uses: actions-ecosystem/action-add-labels@v1.1.0
      with:
        github_token: ${{ github.token }}
        labels: node