name: Check Deploy File

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:

jobs:
  check-project-type:
    uses: DEMGroup/.github/.github/workflows/check-project-type.yml@main

  check-deploy-file:
    needs: [check-project-type]
    if: ${{ needs.check-project-type.outputs.isDotnet == 'true' || needs.check-project-type.outputs.isDotnet == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if deploy.yml exists
        id: check-file
        run: |
          if [ -f ".github/workflows/deploy.yml" ]; then
            exit 0
          else
            exit 1
          fi