name: Release Label Checker

on:
  pull_request:
  workflow_call:

jobs:
  check-project-type:
    uses: DEMGroup/.github/.github/workflows/check-project-type.yml@main

  check_labels:
    needs: [check-project-type]
    if: ${{ contains(fromJson('["opened", "unlabeled","labeled","reopened","synchronize","ready_for_review"]'), github.event.action) }}
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release/major,release/minor,release/patch,release/skip
          repo_token: ${{ secrets.GITHUB_TOKEN }}