name: Release Label Checker

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:

jobs:
  check_labels:
    if: contains(fromJson('["labeled", "unlabeled", "opened", "edited", "reopened","synchronize","ready_for_review"]'), github.event.action)
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release/major,release/minor,release/patch,release/skip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
