name: Release Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.json'

jobs:
  check-project-type:
    uses: ./.github/workflows/check-project-type.yml

  check_labels:
    needs: [check-project-type]

    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release/major,release/minor,release/patch,release/skip
          repo_token: ${{ secrets.GITHUB_TOKEN }}